---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  pull: if-not-exists
  settings:
    username: bkanis
    password:
      from_secret: gitea_password
    registry: gitea.kanis.dev
    repo: gitea.kanis.dev/${DRONE_REPO}
    mirror: http://registry:5000
    insecure: false
    dockerfile:
      from_secret: docker_file
    auto_tag: true
    auto_tag_suffix: linux-amd64
    cache_from: gitea.kanis.dev/${DRONE_REPO}:linux-amd64
  when:
    event:
    - push
    - tag
    - promote

image_pull_secrets:
  - dockerconfigjson

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: publish
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: gitea.kanis.dev
    repo: gitea.kanis.dev/${DRONE_REPO}
    mirror: http://registry:5000
    insecure: false
    dockerfile:
      from_secret: docker_file_arm64
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username: bkanis
    password:
      from_secret: gitea_password
    cache_from: gitea.kanis.dev/${DRONE_REPO}:linux-arm64
  when:
    event:
    - push
    - tag
    - promote

image_pull_secrets:
  - dockerconfigjson

---
kind: pipeline
type: docker
name: manifest-plugin

steps:
  - name: push to docker manifest
    image: plugins/manifest
    settings: 
      username: bkanis
      password:
        from_secret: gitea_password
      target: "gitea.kanis.dev/${DRONE_REPO}:latest"
      template: "gitea.kanis.dev/${DRONE_REPO}:OS-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64/v8
      ignore_missing: true

image_pull_secrets:
- dockerconfigjson

trigger:
  event:
  - push
  - tag
  - promote

depends_on:
- linux-amd64
- linux-arm64