---

kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: gitea.kanis.dev
    repo: gitea.kanis.dev/${DRONE_REPO}
    mirror: http://127.0.0.1:5000
    insecure: true
    dockerfile:
      from_secret: docker_file
    auto_tag: true
    auto_tag_suffix: linux-amd64
    failure: ignore
    username:
      from_secret: gitea_username
    password:
      from_secret: gitea_password
  when:
    event:
    - push
    - tag
    - promote
---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: publish
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: gitea.kanis.dev
    repo: gitea.kanis.dev/${DRONE_REPO}
    mirror: http://127.0.0.1:5000
    insecure: true
    dockerfile:
      from_secret: docker_file_arm64
    auto_tag: true
    auto_tag_suffix: linux-arm64
    failure: ignore
    username:
      from_secret: gitea_username
    password:
      from_secret: gitea_password
  when:
    event:
    - push
    - tag
    - promote
# ---
# kind: pipeline
# type: docker
# name: linux-arm

# platform:
#   arch: arm
#   os: linux

# steps:
# - name: publish
#   image: plugins/docker
#   pull: if-not-exists
#   settings:
#     registry: gitea.kanis.dev
#     repo: gitea.kanis.dev/${DRONE_REPO}
#     mirror: http://127.0.0.1:5000
#     insecure: true
#     dockerfile: docker/Dockerfile.arm
#       from_secret: docker_file_arm64
#     auto_tag: true
#     auto_tag_suffix: linux-arm
#     failure: ignore
#     username:
#       from_secret: gitea_username
#     password:
#       from_secret: gitea_password
#   when:
#     event:
#     - push
#     - tag
#     - promote
# ---
# kind: pipeline
# type: docker
# name: manifest-direct

# services:
#   - name: docker
#     image: docker:dind
#     volumes:
#       - name: dockersock
#         path: /var/run

# steps:
#   - name: create and push manifest
#     image: docker:dind
#     pull: if-not-exists
#     volumes:
#       - name: dockersock
#         path: /var/run
#     commands:
#       - docker manifest create --insecure gitea.kanis.dev/${DRONE_REPO}:latest gitea.kanis.dev/${DRONE_REPO}:linux-amd64 gitea.kanis.dev/${DRONE_REPO}:linux-arm64
#       - docker manifest push --insecure gitea.kanis.dev/${DRONE_REPO}:latest

# volumes:
#   - name: dockersock
#     temp: {}

# trigger:
#   event:
#   - push
#   - tag
#   - promote

# depends_on:
# - linux-amd64
# - linux-arm64
# # - linux-arm

---
kind: pipeline
type: docker
name: manifest-plugin

steps:
  - name: push to docker manifest
    image: plugins/manifest
    settings: 
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_password
      target: "gitea.kanis.dev/${DRONE_REPO}:latest"
      template: "gitea.kanis.dev/${DRONE_REPO}:OS-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true

trigger:
  event:
  - push
  - tag
  - promote

depends_on:
- linux-amd64
- linux-arm64
# - linux-arm