---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: gitea:3000
    repo: gitea:3000/${DRONE_REPO}
    mirror: http://registry:5000
    insecure: true
    dockerfile:
      from_secret: docker_file
    auto_tag: true
    auto_tag_suffix: linux-amd64
    failure: ignore
    username: bkanis
    password:
      from_secret: gitea_password
  when:
    event:
    - push
    - tag
    - promote

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: publish
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: gitea.kanis.dev
    repo: gitea.kanis.dev/${DRONE_REPO}
    mirror: http://registry:5000
    insecure: true
    dockerfile:
      from_secret: docker_file_arm64
    auto_tag: true
    auto_tag_suffix: linux-arm64
    failure: skip
    username: bkanis
    password:
      from_secret: gitea_password
  when:
    event:
    - push
    - tag
    - promote 

# ---
# kind: pipeline
# type: docker
# name: linux-arm

# platform:
#   arch: arm
#   os: linux

# steps:
# - name: publish
#   image: plugins/docker
#   pull: if-not-exists
#   settings:
#     registry: gitea:3000
#     repo: gitea:3000/${DRONE_REPO}
#     mirror: http://registry:5000
#     insecure: true
#     dockerfile: docker/Dockerfile.arm
#       from_secret: docker_file_arm64
#     auto_tag: true
#     auto_tag_suffix: linux-arm
#     failure: ignore
#     username:
#       from_secret: gitea_username
#     password:
#       from_secret: gitea_password
#   when:
#     event:
#     - push
#     - tag
#     - promote

---
kind: pipeline
type: docker
name: manifest-plugin

steps:
  - name: push to docker manifest
    image: plugins/manifest
    settings: 
      username: bkanis
      password:
        from_secret: gitea_password
      target: "gitea.kanis.dev/${DRONE_REPO}:latest"
      template: "gitea.kanis.dev/${DRONE_REPO}:OS-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true

trigger:
  event:
  - push
  - tag
  - promote

depends_on:
- linux-amd64
- linux-arm64
# - linux-arm