kind: pipeline
type: docker
name: Gitea Build

steps:
- name: build
  image: plugins/docker
  settings:
    registry: gitea.kanis.dev
    repo: gitea.kanis.dev/bkanis/flame
    autotag: true 
    tags: latest
    username:
      from_secret: gitea_username
    password:
      from_secret: gitea_password
    insecure: true